[workspace]
resolver = "3"
members = ["af-alfred-workflow", "xtasks/*"]

[workspace.package]
version = "0.11.176"
edition = "2024"
repository = "https://github.com/smykla-skalski/af"
license = "MIT"

[workspace.dependencies]
af = { path = "" }
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive", "env", "string", "wrap_help"] }
clap-verbosity-flag = "3.0.4"
clap_complete_command = "0.6.1"
cli-clipboard = "0.4.0"
clio = { version = "0.3.5", features = ["clap-parse"] }
console = "0.16.3"
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
fern = { version = "0.7.1", features = ["colored"] }
git2 = "0.21.0"
glob = "0.3.3"
humantime = "2.3.0"
indicatif = "0.18.4"
indicatif-log-bridge = "0.2.3"
log = "0.4.29"
octocrab = "0.49.5"
phf = { version = "0.13.1", features = ["macros"] }
rayon = "1.11.0"
regex = "1.12.3"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["rt", "rt-multi-thread", "macros", "process"] }
url = "2.5.8"

[package]
name = "af"
version = "0.11.176"
edition = "2024"
repository = "https://github.com/smykla-skalski/af"
license = "MIT"

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap-verbosity-flag.workspace = true
clap_complete_command.workspace = true
cli-clipboard.workspace = true
clio.workspace = true
console.workspace = true
dialoguer.workspace = true
fern.workspace = true
git2.workspace = true
glob.workspace = true
humantime.workspace = true
indicatif.workspace = true
indicatif-log-bridge.workspace = true
log.workspace = true
octocrab.workspace = true
phf.workspace = true
rayon.workspace = true
regex.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[lib]
name = "af"
path = "src/af/lib.rs"
doctest = false

[[bin]]
name = "af"
test = false
doc = false

[dev-dependencies]
tempfile = "=3.27.0"
