[tools]
pandoc = "3.11"

# Build

[tasks."build::prod"]
description = "Build the production binary"
run = "cargo build --release --locked"

[tasks.build]
description = "Build the project"
depends = ["build::**"]

# Install

[tasks."install::prod"]
description = "Install the production binary locally"
run = 'CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}" cargo install --path . --locked --force'

[tasks.install]
description = "Install the project locally"
depends = ["install::**"]

# Lint

[tasks.lint]
description = "Run lint checks"
run = "cargo clippy --all-targets --all-features"

[tasks."lint::fix"]
description = "Run lint fixes"
run = "cargo clippy --fix --all-targets --all-features --allow-dirty --allow-staged"

[tasks.test]
description = "Run tests"
run = "cargo test --all --verbose"

[tasks.check]
description = "Run project checks"
depends = ["lint", "test"]

# Gen

[tasks."gen::docs::markdown"]
description = "Generate markdown documentation"
run = """
cargo genmd
for f in docs/*.md; do
    pandoc --from markdown --to gfm --wrap none --output "$f" "$f"
done
"""

[tasks."gen::docs::man"]
description = "Generate manual page"
run = "cargo genman"

[tasks."gen::docs"]
description = "Generate documentation"
depends = ["gen::docs::**"]

[tasks.gen]
description = "Generate everything"
depends = ["gen::**"]

# Clean

[tasks."clean::gen::docs::markdown"]
description = "Clean generated markdown documentation"
run = "rm -f docs/af.md"

[tasks."clean::gen::docs::man"]
description = "Clean generated manual page"
run = "rm -rf docs/man"

[tasks."clean::gen::docs"]
description = "Clean generated documentation"
depends = ["clean::gen::docs::**"]
run = "rm -rf docs"

[tasks."clean::gen"]
description = "Clean everything generated"
depends = ["clean::gen::**"]

[tasks.clean]
description = "Clean everything"
depends = ["clean::**"]
