name: "Nix"

on:
  pull_request:
    branches:
    - "main"
    paths:
    - "flake.nix"
    - "flake.lock"
    - "src/**/*"
    - "Cargo.*"

  push:
    branches:
    - "main"
    paths:
    - "flake.nix"
    - "flake.lock"
    - "src/**/*"
    - "Cargo.*"

  schedule:
  - cron: "0 0 1 * *"

  merge_group: {}

  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  nix-build:
    runs-on: ubuntu-24.04
    environment: ci

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: "Install Nix"
      uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

    - name: "Build with Nix"
      run: nix build .#af --print-build-logs

    - name: "Verify binary"
      run: ./result/bin/af --version

    - name: "Check flake"
      run: nix flake check
