name: "Trigger Bump"

on:
  schedule:
  - cron: "0 1 * * *"

  workflow_dispatch: {}

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  ##############################################################################
  #                            CHECK IF SHOULD BUMP                            #
  ##############################################################################

  check-if-should-bump:
    runs-on: ubuntu-24.04

    outputs:
      bump: ${{ steps.should-bump.outputs.bump }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: "Generate GitHub App Token"
      id: github-app-token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        app-id: ${{ vars.SMYKLOT_APP_ID }}
        private-key: ${{ secrets.SMYKLOT_APP_PRIVATE_KEY }}

    - name: "Define if version should be bumped"
      id: should-bump
      env:
        GH_TOKEN: ${{ steps.github-app-token.outputs.token }}
      run: |
        last_tag="$(gh api repos/:owner/:repo/tags --paginate --jq '.[0].name')"
        if ! git diff --quiet "$last_tag...HEAD" -- .github/scripts .github/workflows src Cargo.toml Cargo.lock xtasks; then
          echo "bump=true" >> "$GITHUB_OUTPUT"
        fi

  ##############################################################################
  #                               BUMP AND BUILD                               #
  ##############################################################################

  bump-and-build:
    needs: check-if-should-bump
    if: needs.check-if-should-bump.outputs.bump == 'true'
    uses: ./.github/workflows/__bump-and-build.yml
    secrets: inherit
